language: java
jdk: openjdk8
addons:
  sonarcloud:
    organization: "codeiscoffee"
    token:
      secure: $SONAR
script:
  - jdk_switcher use openjdk8
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
