language: java
jdk:
	- oraclejdk8
addons:
  sonarcloud:
    organization: "codeiscoffee"
    token:
      secure: $SONAR

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
