language: java
jdk: openjdk8
addons:
  sonarcloud:
    organization: "codeiscoffee"
    token: $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=cjk508_Message-Processing-DB
