language: java
jdk: openjdk8
addons:
  sonarcloud:
    organization: "codeiscoffee"
    token:
      secure: "fyPhMd01x3Wn0d2IGLT8xl0tc508lR14YdYsG35ysTC9P+6Lp0f29lSgnaPSH17qll2bAkpq9j8abC+brlkYXnhAW+d/IXyigVM96cAj94K/eQksgGn6/lHBTShXv2Sr0sFH1GF/zT+PhKLkcpE2uhbwLuaob4QcgaoQrlCKj6/avJ1NypA5kXVmdfhr3Wc+iVczjBUwA3a+nFY4PvCUyiweDrNkUmvVTiE7O4uoadTx97dZkZrY/VihsEunMd5zkIfFH8TWn9URroS9IKz5jzWS7yFa2/rmGXni7CV41jwZvHgQd6tgOVgOEQXIWGh6MWgsTfEByWJNf1up0gB+mqWgvbooTy1rrxBr3G2+Yze7cDeoOdN5Yhf5++mf3cHLmq/n/4X7eMzoDcmeIvyrKOLGvxFUyMgmqo1Z3NyPgqRTqt2JLAiSVfCwKUgbEOYoGT9lEgGXheT8IoL5Cy+WnwLpcucp34dG97ble/w2Xqs2hgWS9QiNh4l9jSqrG04IKGoB0kmnj/SOPFkz6JejcVZlzqXfUqsSpciVfPfqLkSa4h/FNDIo89fKF9SFog6IaWjDFe7Cb7NbQ1PZT2j5poYTlnhReoXY8Ixah4IafD++IYpVnnNGvBAXiGzw3QzEsAKJExlImN5G3bA5LbfV6vc2tZ0En+dMRwnT24ZNvC4="
script:
  - jdk_switcher use openjdk8
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
